---
title: 'Scraper original mass: a different approach and its wide range implementation'
author: "Guillermo Bustos-Pérez"
output:
  md_document:
    variant: gfm
bibliography: "References.bib"
csl: "plos-one.csl"
link-citations: true
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div align="justify">   

## **Abstract**   

Predicting the original mass of a retouched scraper has long been a major goal in lithic analysis. It is commonly linked to lithic technological organization of past societies along with notions of stone tool general morphology, standardization through the reduction process, use life, and site occupation patterns. In order to obtain a prediction of original stone tool mass, previous studies have focused on attributes that would remain constant or unaltered through retouch episodes. However, these approaches have provided limited success for predictions and have also remained untested in the framework of successive resharpening episodes. In the research presented here, a set of experimentally knapped flint flakes were successively resharpened as scraper types. After each resharpening episode, four attributes were recorded (scraper mass, height of retouch, maximum thickness and the GIUR index). Four machine learning models were trained using these variables in order to estimate the mass of the flake prior to any retouch. A Random Forest model provided the best results with an r2 value of 0.97 when predicting original flake mass, and a r2 value of 0.84 when predicting percentage of mass lost by retouch.  The Random Forest model has been integrated into an open source and free to use Shiny app. This allows for the wide spread implementation of a highly precise machine learning model for predicting initial mass of flake blanks successively retouched into scrapers.    

**Key words:** experimental archaeology; lithic reduction; flake mass; machine learning.   
# **Introduction**   

Scrapers are some of the most common lithic implements among archaeological lithic assemblages. They are present from the first Oldowan stone tools [@barsky_early_2011; @sahnouni_further_2002; @semaw_26-million-year-old_2003] through to modern ethnographic studies of hunter gatherers [@casamiquela_temas_1978; @gallagher_contemporary_1977; @shott_measuring_2007; @sillitoe_living_2003]. The "reduction model" [@dibble_middle_1995; @dibble_interpretation_1987] suggests that some stone tools (including scrapers) can represent different stages of reuse and modification through retouch. When considering scrapers within the reduction model, an integral concept is that of curation. The initial definition of curation included a series of behavioral patterns related to provisioning strategies [@binford_organization_1979; @renfrew_interassemblage_1973]. However, further authors included into curation behavioral strategies such as tool transport, utilization in a wide range of tasks, anticipated production, hafting, and recycling (after the original tool had been discarded). An alternative definition of curation was proposed by Shott [@shott_exegesis_1996; @shott_tool-class_1989], who defined curation as “the ratio of realized to potential utility”. This new approach to the definition of curation has important implications for lithic analysis and the study of lithic technological organization since it transforms curation into a continuous variable [@shott_exegesis_1996]. Given this new definition, and in the framework of the reduction model, the amount of mass lost by a lithic artifact by reuse/resharpening will be equivalent to its ratio of curation. Both variables (amount in grams and percentage of mass lost by a stone tool) can be empirically calculated in experimental contexts and estimated in archaeological contexts. The presence of scrapers and their curation relates to several aspects of the organization of lithic technology of past societies [@clarkson_holocene_2002; @glauberman_late_2020; @andrefsky_construction_2008; @kuhn_unpacking_1991; @shott_costs_2018; @shott_use_2017]. Amount of curation affects the shape of stone tools at the moment of their discard (thus affecting the morphological variability of stone tool assemblages observed through time). Amount of curation can also relate to raw material sources, with more curated artifacts coming from longer distances. Curation also relates to the selection of technological products for more intensive retouch, or shifts in technological strategies of transport, thus informing about the cultural choices and patterns of past human groups. Finally, curation also relates to tool use and use-wear analysis.   

Because of these reasons, predicting original scraper mass is a major goal in lithic analysis. Thus far, two approaches are employed to estimate the reduction and curation undergone by a retouched artifact. The first approach uses estimations derived from direct measurements on retouch. This has led to the proposal of several indexes using different measurements, such as height of retouch, length of retouched edge or projection of the original angle [@bustos-perez_exploring_2019; @eren_defining_2005; @kuhn_geometric_1990; @morales_measuring_2015]. These indices usually provide good correlation values with mass lost, but they are usually conditioned by flake morphology, direction of retouch, or tool type (laterally retouched scrapers, endscrapers, bifacial products, etc.) and each one uses different scale ranges.    

The second approach aims at estimating original flake mass based on remaining flake features. This approach has the advantage of not being limited by tool type, direction of retouch or flake morphology. Initial work focused on controlled experiments of flake formation using different measures of flake platform (width, depth) and exterior platform angle (EPA) to estimate flake mass [@dibble_platform_1997; @dibble_effect_1995; @dibble_new_1981; @pelcin_formation_1997; @pelcin_controlled_1996]. Some of the reasons to select these features were that they usually remain unaltered in most retouched artefacts. These controlled experiments provided strong explanatory power for the formation of flakes, with flake mass being predicted with an r2 value above 0.8 [@dibble_effect_1995; @li_synthesis_2023]. However, when the same variables are used to predict mass of experimentally knapped flakes, the predictive power of the model diminishes significantly, with r2 values dropping to 0.403 [@davis_quantifying_1998] (0.224 for the same retouched flakes), and 0.384 [@shott_flake_2000]. These results meant an important drawback since, as Dibble [@dibble_comment_1998 :611]


# **References**   

</div> 



